name: docdoc
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  easy_localization: ^3.0.7
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
