
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:269964795582:android:9a60d08938f7acea6dc8ef",
        firebase_cli_token: "1//0333gDPykgyecCgYIARAAGAMSNwF-L9IrSB3Cu04q7nrzJPmtot6U_Rclx_zvl3pDJ7OfCknskvSucbUPa87VburhCUAt_SNV8Sg",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "hdyrshad75@gmail.com",
        release_notes: "First Fastlane Firebase Distribution!"
  )
  end
end